const ADD_MESSAGE = "ADD_MESSAGE";
const ADD_CHAT = "ADD_CHAT";
const DELETE_CHAT = "DELETE_CHAT";
const DELETE_MESSAGES = "DELETE_MESSAGES";
const CREATE_MESSAGES = "CREATE_MESSAGES";
const GET_USERS = 'GET_USERS';
const GET_USERS_LOADING = 'GET_USERS_LOADING';
const GET_USERS_ERROR = 'GET_USERS_ERROR';

export { ADD_MESSAGE, ADD_CHAT, DELETE_CHAT, DELETE_MESSAGES, CREATE_MESSAGES, GET_USERS, GET_USERS_LOADING, GET_USERS_ERROR }