const ADD_MESSAGE = "ADD_MESSAGE";
const ADD_CHAT = "ADD_CHAT";
const DELETE_CHAT = "DELETE_CHAT";
const DELETE_MESSAGES = "DELETE_MESSAGES";
const CREATE_MESSAGES = "CREATE_MESSAGES";
// const GET_USERS = 'GET_USERS';
// const GET_USERS_LOADING = 'GET_USERS_LOADING';
// const GET_USERS_ERROR = 'GET_USERS_ERROR';

export const REGISTER_LOADING = 'REGISTER_LOADING';
export const REGISTER_ERROR = 'RREGISTER_ERROR';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';

export const LOGIN_LOADING = 'LOGIN_LOADING';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const LOGOUT_LOADING = 'LOGOUT_LOADING';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const CLEAN_ERROR = 'CLEAN_ERROR';
export const CHANGE_MESSAGES = 'CHANGE_MESSAGES';

export { ADD_MESSAGE, ADD_CHAT, DELETE_CHAT, DELETE_MESSAGES, CREATE_MESSAGES }