const ADD_MESSAGE = "ADD_MESSAGE";
const ADD_CHAT = "ADD_CHAT";
const DELETE_CHAT = "DELETE_CHAT";
const DELETE_MESSAGES = "DELETE_MESSAGES";
const CREATE_MESSAGES = "CREATE_MESSAGES";

export { ADD_MESSAGE, ADD_CHAT, DELETE_CHAT, DELETE_MESSAGES, CREATE_MESSAGES }